apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-cubestore-router
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: cubestore-router
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.cubestoreRouter.service.port }}
      targetPort: {{ .Values.cubestoreRouter.service.port }}
      protocol: TCP
      name: http
    - port: 3030
      targetPort: 3030
      protocol: TCP
      name: http2
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mysql   
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: cubestore-router
