apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "chart.fullname" . }}-cubestore-worker
  labels:
    app.kubernetes.io/name: {{ include "chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: cubestore-worker
    {{- if .Chart.AppVersion }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    {{- end }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.cubestoreWorker.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  serviceName: {{ include "chart.fullname" . }}-cubestore-worker
  replicas: {{ .Values.cubestoreWorker.replicas | default 2 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: cubestore-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: cubestore-worker
    spec:
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      {{- with .Values.cubestoreWorker.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: cubestore-pv
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-{{ .Chart.Name }}-cubestore-pvc
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.cubestoreWorker.image | quote }}
          imagePullPolicy: {{ .Values.cubestoreWorker.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.cubestoreWorker.service.port }}
              protocol: TCP
          env:
            - name: CUBESTORE_WORKERS
              value: {{ $count := .Values.cubestoreWorker.replicas | int }}{{- $networkAppPort  := .Values.cubestoreWorker.service.port -}}
              {{- range until $count }}{{ $.Release.Name }}-cubejs-cubestore-worker-{{  .  }}.{{ $.Release.Name }}-cubejs-cubestore-worker:{{ $networkAppPort }},{{- end }}
            - name: CUBESTORE_SERVER_NAME
              value: "{{ .Release.Name }}-cubejs-cubestore-worker-0.{{ .Release.Name }}-cubejs-cubestore-worker:10001"
            - name: CUBESTORE_WORKER_PORT
              value: "10001"
            - name: CUBESTORE_REMOTE_DIR
              value: "/cube/data"
            - name: CUBESTORE_META_ADDR
              value: "{{ .Release.Name }}-cubejs-cubestore-router:9999"
            - name: CUBEJS_LOG_LEVEL
              value: "trace"
          volumeMounts:
            - mountPath: /cube/data
              name: cubestore-pv
          {{- with .Values.cubestoreWorker.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.cubestoreWorker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cubestoreWorker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cubestoreWorker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
