apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-cubestore-router
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: cubestore-router
spec:
  type: {{ .Values.cubestoreRouter.service.type }}
  ports:
    - port: {{ .Values.cubestoreRouter.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.cubestoreRouter.service.http2_port }}
      targetPort: http2
      protocol: TCP
      name: http2
    - port: {{ .Values.cubestoreRouter.service.mysql_port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: cubestore-router
