apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-cube-api
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.cubeApi.service.port }}
      targetPort: {{ .Values.cubeApi.service.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: cube-api
