apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  DATABASE_HOST: {{ .Values.DATABASE_HOST | b64enc | quote }}
  DATABASE_USER: {{ .Values.DATABASE_USER | b64enc | quote }}
  DATABASE_PASSWORD: {{ .Values.DATABASE_PASSWORD | b64enc | quote }}
  DATABASE_NAME: {{ .Values.DATABASE_NAME | b64enc | quote }}
  REDIS_HOST: {{ .Values.REDIS_HOST | b64enc | quote }}
  REDIS_PORT: {{ .Values.REDIS_PORT | quote | b64enc }}
  JWT_SECRET: {{ .Values.JWT_SECRET | b64enc | quote }}
  GITHUB_CLIENT_ID: {{ .Values.GITHUB_CLIENT_ID | b64enc | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.GITHUB_CLIENT_SECRET | b64enc | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.GOOGLE_CLIENT_ID | b64enc | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.GOOGLE_CLIENT_SECRET | b64enc | quote }}
  WEB_URL: {{ .Values.WEB_URL | b64enc | quote }}
  API_URL: {{ .Values.API_URL | b64enc | quote }}
  SMTP_USERNAME: {{ .Values.SMTP_USERNAME | b64enc | quote }}
  SMTP_PASSWORD: {{ .Values.SMTP_PASSWORD | b64enc | quote }}
  SMTP_HOST: {{ .Values.SMTP_HOST | b64enc | quote }}
  SMTP_FROM: {{ .Values.SMTP_FROM | b64enc | quote }}
  SMTP_PORT: {{ .Values.SMTP_PORT | quote | b64enc }}
  CUBE_API_URL: {{ .Values.CUBE_API_URL | b64enc | quote }}
  LOOPS_API_KEY: {{ .Values.LOOPS_API_KEY | b64enc | quote }}
