apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  DATABASE_HOST: {{ include "api.databaseHost" . | b64enc | quote }}
  DATABASE_USER: {{ .Values.DATABASE_USER | b64enc | quote }}
  DATABASE_NAME: {{ .Values.DATABASE_NAME | b64enc | quote }}
  DATABASE_SSL_MODE: {{ .Values.DATABASE_SSL_MODE | b64enc | quote }}
  REDIS_HOST: {{ include "api.redisHost" . | b64enc | quote }}
  REDIS_PORT: {{ .Values.REDIS_PORT | b64enc | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.GOOGLE_CLIENT_ID | b64enc | quote }}
  WEB_URL: {{ .Values.WEB_URL | b64enc | quote }}
  API_URL: {{ .Values.API_URL | b64enc | quote }}
  SMTP_HOST: {{ .Values.SMTP_HOST | b64enc | quote }}
  SMTP_PORT: {{ .Values.SMTP_PORT | b64enc | quote }}
  SMTP_FROM: {{ .Values.SMTP_FROM | b64enc | quote }}
