apiVersion: v2
name: enterprise
description: A Helm chart for running Cubejs in Kubernetes 

type: application

version: 0.1.0

appVersion: "1.16.0"

dependencies:
  - name: postgresql
    version: 12.5.7
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    version: 17.11.3
    repository: https://charts.bitnami.com/bitnami