# Override names
nameOverride: ""
fullnameOverride: ""

api:
  image:
    registry: "ghcr.io"
    repository: ci-cube/cicube-api/api
    tag: sha-de8237c
  imagePullSecrets:
    - name: registry-secret
  replicaCount: 1
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      cert-manager.io/cluster-issuer: letsencrypt-prod
    host: "api.cicube.io"
    tls:
      enabled: true
      secretName: ""
    path: /
    pathType: Prefix
  env:
    DATABASE_HOST: "my-release-postgresql"
    DATABASE_USER: "postgres"
    DATABASE_PASSWORD: "test123"
    DATABASE_NAME: "cicube"
    REDIS_HOST: "my-release-redis-master"
    JWT_SECRET: "test-jwt-secret"
    WEB_URL: "http://localhost:3001"
    API_URL: "http://localhost:3001"
    CUBE_API_URL: "http://my-release-cube:4000/cubejs-api/v1"
    GITHUB_CLIENT_ID: ""
    GITHUB_CLIENT_SECRET: ""
    GOOGLE_CLIENT_ID: ""
    GOOGLE_CLIENT_SECRET: ""
    SMTP_USERNAME: ""
    SMTP_PASSWORD: ""
    LOOPS_API_KEY: ""

cube:
  image:
    registry: "ghcr.io"
    repository: ci-cube/cicube-api/cube
    tag: sha-4bbc5a6
  imagePullSecrets:
    - name: registry-secret
  replicaCount: 1
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  service:
    type: ClusterIP
    port: 4000
  env:
    CUBEJS_DB_TYPE: postgres
    CUBEJS_DB_HOST: "my-release-postgresql"
    CUBEJS_DB_USER: "postgres"
    CUBEJS_DB_PASS: "test123"
    CUBEJS_DB_NAME: "cicube"
    CUBEJS_API_SECRET: "test-jwt-secret"
  
  refreshWorker:
    enabled: true
    replicaCount: 1
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi

  cubestore:
    enabled: true
    persistence:
      enabled: true
      size: 1Gi
      storageClass: ""
    router:
      replicaCount: 1
      resources:
        limits:
          cpu: 1000m
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 1Gi
      service:
        type: ClusterIP
        port: 9999
    worker:
      replicaCount: 1
      resources:
        limits:
          cpu: 1000m
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 1Gi
      service:
        type: ClusterIP
        port: 9001

postgresql:
  auth:
    postgresPassword: "test123"
    database: "cicube"
  primary:
    persistence:
      size: 1Gi

redis:
  auth:
    enabled: false
  architecture: standalone
  master:
    persistence:
      size: 1Gi