# Global configurations
global:
  # Image pull secrets for all deployments
  imagePullSecrets:
    - name: registry-secret
  
  # Shared secrets configuration for all components
  secrets:
    postgresql:
      password: "postgres123"
      host: ""  # Optional: If not set, will use {{ .Release.Name }}-postgresql
    redis:
      host: ""  # Optional: If not set, will use {{ .Release.Name }}-redis-master
    jwt:
      secret: "secret123456789"
    github:
      clientId: ""
      clientSecret: ""
      appName: ""
    google:
      clientSecret: ""
    smtp:
      username: ""
      password: ""
    loops:
      apiKey: ""

# Component enablement
api:
  enabled: true
  replicaCount: 1
  
  image:
    repository: ghcr.io/ci-cube/cicube-api/api
    tag: "sha-d961d49"
    pullPolicy: IfNotPresent

  imagePullSecrets:
    - name: registry-secret

  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    create: true
    annotations: {}
    name: ""

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    annotations:
      cert-manager.io/issuer: "letsencrypt-prod"
    hosts:
      - host: api2.cicube.io
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: "api-tls"
        hosts:
          - api2.cicube.io

  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80

  nodeSelector: {}

  selectorLabels: {}

  tolerations: []

  affinity: {}
  
  # Redis configurations for Bitnami Redis chart
  redis:
    enabled: true
    global:
      redis:
        password: null
    architecture: standalone
    auth:
      enabled: false
    master:
      persistence:
        enabled: true
      service:
        ports:
          redis: 6379
    replica:
      replicaCount: 0
      persistence:
        enabled: false

# API Secret Values
  DATABASE_USER: "postgres"
  DATABASE_NAME: "halley"
  DATABASE_SSL_MODE: "false"
  REDIS_PORT: "6379"
  GOOGLE_CLIENT_ID: ""
  WEB_URL: "https://app2.cicube.io"
  API_URL: "https://api2.cicube.io"
  SMTP_HOST: "email-smtp.eu-west-1.amazonaws.com"
  SMTP_PORT: "2465"
  SMTP_FROM: '"CICube Enterprise" <info@cicube.io>'

cubejs:
  enabled: true
  annotations: 
    reloader.stakater.com/auto: "true"
  
  imagePullSecrets:
    - name: registry-secret

  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    create: true
    annotations: {}
    name: ""

  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}

  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80

  ingress:
    enabled: true
    annotations:
      cert-manager.io/issuer: "letsencrypt-prod"
    hosts:
      - host: cube2.cicube.io
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: "cube-tls"
        hosts:
          - cube2.cicube.io

  cubeApi:
    image: ghcr.io/ci-cube/cicube-api/cube
    tag: "sha-8695f0c"
    pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 4000
      service_port: 4000
    replicas: 1

  cubeRefreshWorker:
    image: ghcr.io/ci-cube/cicube-api/cube
    tag: "sha-8695f0c"
    pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 80
      service_port: 80
    replicas: 1

  cubestoreRouter:
    image: "cubejs/cubestore"
    pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 9999
      service_port: 9999
      http2_port: 3030
      mysql_port: 3306
    replicas: 1
    env:
      var:
        CUBESTORE_REMOTE_DIR: "/cube/data"
        CUBESTORE_META_PORT: "9999"
        CUBESTORE_SERVER_NAME: "ci-cube-cubejs-cubestore-router:9999"
        CUBEJS_LOG_LEVEL: "trace"

  cubestoreWorker:
    image: "cubejs/cubestore"
    pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 10001
      service_port: 10001
    replicas: 1
    env:
      var:
        CUBESTORE_SERVER_NAME: "ci-cube-cubejs-cubestore-worker-0.ci-cube-cubejs-cubestore-worker:10001"
        CUBESTORE_WORKER_PORT: "10001"
        CUBESTORE_REMOTE_DIR: "/cube/data"
        CUBESTORE_META_ADDR: "ci-cube-cubejs-cubestore-router:9999"
        CUBEJS_LOG_LEVEL: "trace"

# PostgreSQL configuration
postgresql:
  enabled: true
  auth:
    existingSecret: "{{ .Release.Name }}-app-secrets"
    secretKeys:
      adminPasswordKey: postgresql-password
      userPasswordKey: postgresql-password
    username: "postgres"
    database: "halley"
  primary:
    persistence:
      enabled: true
      size: 10Gi

# App configuration
app:
  enabled: true
  replicaCount: 1
  
  image:
    repository: ghcr.io/ci-cube/cicube-app/app
    tag: "sha-6b59111"
    pullPolicy: IfNotPresent

  imagePullSecrets:
    - name: registry-secret

  nameOverride: ""
  fullnameOverride: ""

  service:
    type: ClusterIP
    port: 3000

  env:
    VITE_API_URL: "https://api2.cicube.io"
    VITE_WEB_URL: "https://app2.cicube.io"
    VITE_CUBE_API_URL: "https://cube2.cicube.io"
    VITE_GA_MEASUREMENT_ID: ""
    VITE_GOOGLE_CLIENT_ID: ""

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80

  serviceAccount:
    create: true
    annotations: {}
    name: ""

  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}

  ingress:
    enabled: true
    annotations:
      cert-manager.io/issuer: "letsencrypt-prod"
    hosts:
      - host: app2.cicube.io
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: "app-tls"
        hosts:
          - app2.cicube.io

  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}      



