apiVersion: v1
kind: Service
metadata:
  name: {{ include "enterprise.fullname" . }}-api
  labels:
    {{- include "enterprise.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "enterprise.selectorLabels" . | nindent 4 }} 