apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "enterprise.fullname" . }}-api-post-install
  labels:
    {{- include "enterprise.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "enterprise.fullname" . }}-api-post-install
      labels:
        {{- include "enterprise.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: post-install
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["npm", "run", "migrate"]
          env:
            - name: DATABASE_HOST
              value: {{ .Values.DATABASE_HOST | quote }}
            - name: DATABASE_USER
              value: {{ .Values.DATABASE_USER | quote }}
            - name: DATABASE_PASSWORD
              value: {{ .Values.DATABASE_PASSWORD | quote }}
            - name: DATABASE_NAME
              value: {{ .Values.DATABASE_NAME | quote }}
            - name: REDIS_HOST
              value: {{ .Release.Name }}-redis-master
            - name: JWT_SECRET
              value: {{ .Values.JWT_SECRET | quote }}
            - name: GITHUB_CLIENT_ID
              value: {{ .Values.GITHUB_CLIENT_ID | quote }}
            - name: GITHUB_CLIENT_SECRET
              value: {{ .Values.GITHUB_CLIENT_SECRET | quote }}
            - name: GOOGLE_CLIENT_ID
              value: {{ .Values.GOOGLE_CLIENT_ID | quote }}
            - name: GOOGLE_CLIENT_SECRET
              value: {{ .Values.GOOGLE_CLIENT_SECRET | quote }}
            - name: WEB_URL
              value: {{ .Values.WEB_URL | quote }}
            - name: API_URL
              value: {{ .Values.API_URL | quote }}
            - name: SMTP_USERNAME
              value: {{ .Values.SMTP_USERNAME | quote }}
            - name: SMTP_PASSWORD
              value: {{ .Values.SMTP_PASSWORD | quote }}
            - name: CUBE_API_URL
              value: {{ .Values.CUBE_API_URL | quote }}
            - name: LOOPS_API_KEY
              value: {{ .Values.LOOPS_API_KEY | quote }}