apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-app-secrets
type: Opaque
data:
  # Database credentials
  postgresql-password: {{ .Values.global.secrets.postgresql.password | default "postgres123" | b64enc | quote }}
  
  # JWT secret
  jwt-secret: {{ .Values.global.secrets.jwt.secret | default "secret123456789" | b64enc | quote }}
  
  # OAuth credentials
  github-client-id: {{ .Values.global.secrets.github.clientId | b64enc | quote }}
  github-client-secret: {{ .Values.global.secrets.github.clientSecret | b64enc | quote }}
  github-app-name: {{ .Values.global.secrets.github.appName | default "cicube-2-enterprise-test-app" | b64enc | quote }}
  google-client-secret: {{ .Values.global.secrets.google.clientSecret | b64enc | quote }}
  
  # SMTP credentials
  smtp-username: {{ .Values.global.secrets.smtp.username | b64enc | quote }}
  smtp-password: {{ .Values.global.secrets.smtp.password | b64enc | quote }}
  
  # Other API keys
  loops-api-key: {{ .Values.global.secrets.loops.apiKey | b64enc | quote }} 