apiVersion: v1
kind: Service
metadata:
  name: {{ include "enterprise.fullname" . }}-cube
  labels:
    {{- include "enterprise.labels" . | nindent 4 }}
spec:
  type: {{ .Values.cube.service.type }}
  ports:
    - port: {{ .Values.cube.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "enterprise.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: cube 