apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cubestore-router
  labels:
    {{- include "enterprise.labels" . | nindent 4 }}
{{- if .Values.annotations }}
  annotations: {{ toYaml .Values.annotations | nindent 4 }}
{{- end }}
spec:
  serviceName: cubestore-router
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.cubestoreRouter.replicas }}
  {{- end }}
  selector:
    matchLabels:
      cubejsApp: cubestoreRouter
  template:
    metadata:
      labels:
        cubejsApp: cubestoreRouter
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "enterprise.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: cubestore-pv
          persistentVolumeClaim:
            claimName: cubestore-pvc
      containers:
        - name: cubestore-router
          env:
          - name: CUBESTORE_WORKERS
            value: {{ $count := .Values.cubestoreWorker.replicas | int }}{{- $networkAppPort  := .Values.cubestoreWorker.service.port -}}
            {{- range until $count }}cubestore-worker-{{  .  }}.cubestore-worker:{{ $networkAppPort }},
            {{- end }}
          envFrom:
          - configMapRef:
              name: {{ .Values.cubestoreRouter.configmap.name }}
          command: ["/bin/sh","-c"]
          args: ["unset CUBESTORE_WORKER_PORT; ./cubestored"]
          volumeMounts:
            - mountPath: /cube/data
              name: cubestore-pv
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.cubestoreRouter.image }}"
          imagePullPolicy: {{ .Values.cubestoreRouter.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.cubestoreRouter.service.port }}
              protocol: TCP
            - name: http2
              containerPort: 3030
              protocol: TCP 
            - name: mysql
              containerPort: 3306
              protocol: TCP   
          resources:
            {{- toYaml .Values.cubestoreRouter.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
