apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cube
  labels:
    app: {{ .Release.Name }}-cube
    {{- include "enterprise.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.cube.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-cube
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-cube
        {{- include "enterprise.labels" . | nindent 8 }}
    spec:
      {{- with .Values.cube.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: cube-pv
          persistentVolumeClaim:
            claimName: cube-pvc
      containers:
        - name: cube
          image: "{{ .Values.cube.image.registry }}/{{ .Values.cube.image.repository }}:{{ .Values.cube.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.cube.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Values.cube.configmap.name }}
          resources:
            {{- toYaml .Values.cube.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /cube/conf
              name: cube-pv
          livenessProbe:
            httpGet:
              path: /readiness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readiness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3