apiVersion: apps/v1
kind: Deployment
metadata:
  name: cube-refresh-worker
  labels:
    {{- include "enterprise.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.cubeReplicas.cubeRefreshWorker }}
  selector:
    matchLabels:
      cubejsApp: cubeRefreshWorker
  template:
    metadata:
      labels:
        cubejsApp: cubeRefreshWorker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          envFrom:
          - configMapRef:
              name: {{ .Values.cubeRefreshWorker.configmap.name }}
          image: {{ .Values.cubeRefreshWorker.image }}
          imagePullPolicy: {{ .Values.cubeRefreshWorker.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.cubeRefreshWorker.service.port }}
              protocol: TCP 