apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cube
  labels:
    app: {{ .Release.Name }}-cube
spec:
  replicas: {{ .Values.cube.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-cube
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-cube
    spec:
      {{- with .Values.cube.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: cube
          image: "{{ .Values.cube.image.registry }}/{{ .Values.cube.image.repository }}:{{ .Values.cube.image.tag }}"
          ports:
            - containerPort: 4000
          resources:
            {{- toYaml .Values.cube.resources | nindent 12 }}
          env:
            {{- range $key, $value := .Values.cube.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /readiness
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readiness
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 10 