{{- if .Values.cube.cubestore.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "enterprise.fullname" . }}-cubestore-worker
  labels:
    {{- include "enterprise.labels" . | nindent 4 }}
spec:
  type: {{ .Values.cube.cubestore.worker.service.type }}
  clusterIP: None
  ports:
    - port: {{ .Values.cube.cubestore.worker.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "enterprise.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: cubestore-worker
{{- end }} 