{{- if .Values.cube.cubestore.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cubestore-router
  labels:
    app: {{ .Release.Name }}-cubestore-router
    {{- include "enterprise.labels" . | nindent 4 }}
spec:
  type: {{ .Values.cube.cubestore.router.service.type }}
  ports:
    - port: {{ .Values.cube.cubestore.router.service.service_port }}
      targetPort: {{ .Values.cube.cubestore.router.service.port }}
      protocol: TCP
      name: http
    - port: 3030
      targetPort: 3030
      protocol: TCP
      name: http2
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mysql
  selector:
    app: {{ .Release.Name }}-cubestore-router
{{- end }} 