apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cube
  labels:
    app: {{ .Release.Name }}-cube
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-cube 